routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');
Route::post('/contact_us', 'ContactUsController@send')->name('contact_us');
Route::get('/product/{slug}', 'HomeController@products')->name('product');

Route::group(['middleware' => ['auth']], function () {
    Route::get('/my/profile', 'UserController@profile')->name('my.profile');
    Route::post('/my/profile', 'UserController@update')->name('my.profile.update');
    Route::get('/my/wallet', 'WalletController@index')->name('my.wallet');
    Route::get('/my/orders', 'OrderController@index')->name('my.orders');
    Route::get('/fund-wallet', 'WalletController@fund')->name('fund.wallet');
    Route::post('/fund-wallet', 'WalletController@storeTransaction')->name('fund.wallet.create');
    Route::post('/order', 'OrderController@add')->name('order.create');
    Route::patch('/transaction/status', 'TransactionController@toggleStatus')->name('transaction.update.status');
});


Route::group(['namespace' => 'Auth'], function () {
    Route::get('/register', 'RegistrationController@showForm')->name('register')->middleware('guest');
    Route::post('/register', 'RegistrationController@register')->name('register.submit')->middleware('guest');

    Route::get('/login', 'LoginController@showForm')->name('login');
    Route::get('/logout', 'LoginController@logout')->name('logout');
    Route::post('/login', 'LoginController@authenticate')->name('login.submit');

    Route::post('/change-password', 'PasswordController@change')->name('change.password')->middleware('auth');
    Route::get('/forgot-password', 'PasswordController@showForm')->name('forgot.password')->middleware('guest');
    Route::post('/forgot-password', 'PasswordController@requestReset')->name('password.request.reset')->middleware('guest');
    Route::get('/password/reset/{token}', 'PasswordController@resetForm')->middleware('guest');
    Route::post('/password/reset', 'PasswordController@resetPassword')->name('password.reset')->middleware('guest');
});

Route::get('/{page}', 'PageController@index');

Route::post('/monnify/webhook', 'WalletController@monnifyWebhook');

app/Order.php
<?php

namespace App;

use App\Notifications\OrderCancelled;
use App\Notifications\OrderCompleted;

/**
 * Class Order
 * @package App
 */
class Order extends BaseModel
{
    const STATUS_PENDING = 0;
    const STATUS_PROCESSING = 1;
    const STATUS_COMPLETED = 2;
    const STATUS_CANCELLED = 9;

    const status = [
        0 => 'Pending',
        1 => 'Processing',
        2 => 'Completed',
        9 => 'Cancelled'
    ];

    protected $fillable = [
        'user_id',
        'product_id',
        'variant_id',
        'amount',
        'phone',
        'status',
        'services'
    ];

    public function getStatusReadableAttribute()
    {
        return self::status[$this->status];
    }

    public static function boot()
    {
        parent::boot();

        static::creating(function ($model) {
            $model->order_number = static::generateOrderNumber();
        });

        static::created(function ($model) {
            if ($model->status == self::STATUS_COMPLETED)
                static::notifyOrderCompleted($model);
        });

        static::updated(function ($model) {
            // If order was cancelled
            if ($model->status == self::STATUS_CANCELLED && $model->getOriginal('status') == self::STATUS_PROCESSING) {
                static::refundWallet($model);
                static::notifyOrderCancelled($model);
            }

            // If order was Completed
            if ($model->status == self::STATUS_COMPLETED && $model->getOriginal('status') == self::STATUS_PROCESSING)
                static::notifyOrderCompleted($model);
        });
    }

    private static function refundWallet($model)
    {
        return Transaction::create([
            'amount' => $model->amount,
            'user_id' => $model->user_id,
            'status' => Transaction::STATUS_COMPLETED,
            'type' => Transaction::TYPE_CREDIT
        ]);
    }

    private static function notifyOrderCompleted($model)
    {
        try {
            $model->user->notify(new OrderCompleted($model));
        } catch(\Exception $e) {

        }
    }

    private static function notifyOrderCancelled($model)
    {
        try {
            $model->user->notify(new OrderCancelled($model));
        } catch(\Exception $e) {

        }
    }

    private static function generateOrderNumber()
    {
        $order_number = str_pad(rand(1, 999999), 6, '0', STR_PAD_LEFT);

        if (Order::where('order_number', $order_number)->first())
            return static::generateOrderNumber();

        return $order_number;
    }

    public function product()
    {
        return $this->belongsTo(Product::class, 'product_id');
    }

    public function variant()
    {
        return $this->belongsTo(ProductVariation::class, 'variant_id');
    }

    public function user()
    {
        return $this->belongsTo(User::class, 'user_id');
    }
}

app/Transaction.php
<?php
declare(strict_types=1);

namespace App;

use App\Notifications\WalletCredited;

/**
 * Class Transaction
 * @package App
 */
class Transaction extends BaseModel
{
    const TYPE_CREDIT = 1;
    const TYPE_DEBIT = 2;

    const type = [
        1 => 'Credit',
        2 => 'Debit'
    ];

    const STATUS_PENDING = 0;
    const STATUS_COMPLETED = 1;

    const status = [
        0 => 'Pending',
        1 => 'Completed'
    ];

    protected $fillable = [
//        'reference',
        'amount',
        'user_id',
        'status',
        'type',
        'monnify_reference'
    ];

    public function getStatusReadableAttribute()
    {
        return self::status[$this->status];
    }

    public function getTypeReadableAttribute()
    {
        return self::type[$this->type];
    }

    public static function boot()
    {
        parent::boot();

        static::creating(function ($model) {
            $model->reference = static::generateReference();
        });

        static::created(function ($model) {
            if ($model->status == self::STATUS_COMPLETED)
                static::updateWalletBalance($model);

        });

        static::updated(function ($model) {
            if ($model->status == self::STATUS_COMPLETED)
                static::updateWalletBalance($model);
        });
    }

    /**
     * Generate a unique transaction reference
     * @return string
     */
    protected static function generateReference(): string
    {
        $ref = bin2hex(openssl_random_pseudo_bytes(3)) . substr((string)time(), -4);

        if (static::where('reference', $ref)->count() > 0) return static::generateReference();

        return $ref;
    }

    protected static function updateWalletBalance(Transaction $transaction)
    {
        $wallet = Wallet::where('user_id', $transaction->user_id)->first();

        if ($transaction->type == self::TYPE_CREDIT) {
            $wallet->update([
                'current_balance' => $transaction->amount + $wallet->current_balance,
                'earned' => $transaction->amount + $wallet->earned
            ]);

            $transaction->user->notify(new WalletCredited($transaction));
        }
        else
            $wallet->update([
                'current_balance' => $wallet->current_balance - $transaction->amount,
                'spent' => $transaction->amount + $wallet->spent
            ]);
    }

    public function user()
    {
        return $this->belongsTo(User::class, 'user_id');
    }
}

app/Wallet.php
<?php
declare(strict_types=1);

namespace App;

/**
 * Class Wallet
 * @package App
 */
class Wallet extends BaseModel
{
    protected $fillable = [
        'user_id',
        'current_balance',
        'earned',
        'spent'
    ];
}

app/Http/Controllers/WalletController.php
<?php
declare(strict_types=1);

namespace App\Http\Controllers;

use App\Http\Traits\BankTraits;
use App\Repositories\TransactionRepository;
use App\Transaction;
use App\User;
use App\Wallet;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;

/**
 * Class WalletController
 * @package App\Http\Controllers
 */
class WalletController extends Controller
{
    use BankTraits;
    /**
     * @var TransactionRepository
     */
    private $transactionRepo;

    const MONNIFY_SUCCESSFUL_TRANSCTION = 'SUCCESSFUL_TRANSACTION';

    /**
     * WalletController constructor.
     * @param TransactionRepository $trans
     */
    public function __construct(TransactionRepository $trans)
    {
        $this->transactionRepo = $trans;
    }

    public function index()
    {
        $wallet = Wallet::where('user_id', auth()->user()->id)->first();

        $transactions = Transaction::where('user_id', auth()->user()->id)->latest()->take(10)->get();

        return view('wallet.index', compact('wallet', 'transactions'));
    }

    public function fund()
    {
        if (! ($user = auth()->user())->hasBank()) {
            try {
                static::createBank($user);
            } catch (\Exception $e) {
                Log::error($e->getMessage());
            }
        }

        $bank = $user->bank;
        return view('wallet.fund', compact('bank'));
    }

    public function storeTransaction(Request $request)
    {
        $this->validate($request, [
            'amount' => 'required'
        ]);

        $data = [
            'amount' => $request->input('amount'),
            'user_id' => $request->user()->id,
            'status' => Transaction::STATUS_PENDING,
            'type' => Transaction::TYPE_CREDIT
        ];

        $tranx = $this->transactionRepo->create($data);

        return response()->json([
            'message' => 'Transaction saved successfully',
            'data' => $tranx
        ]);
    }

    public function monnifyWebhook(Request $request)
    {
//        $secret = 'G4BUR9NFKCUX5YTVM86A9ZK2X44LBA69';
//        $hash = $this->computeSHA512TransactionHash(json_encode($request->json()->all()), $secret);
//
//        if ($hash !== $request->header('monnify-signature')) {
//            Log::error('Hash error');
//            Log::error($hash);
//            Log::error($request->header('monnify-signature'));
//            return;
//        }
//
//
//        Log::error(json_encode($request->json()->all()));

        if ($request->json('eventType') === self::MONNIFY_SUCCESSFUL_TRANSCTION) {
            $eventData = (object)$request->json('eventData');

            $data = [
                'amount' => $eventData->amountPaid,
                'user_id' => User::where('email', $eventData->customer['email'])->first()->id,
                'status' => Transaction::STATUS_COMPLETED,
                'type' => Transaction::TYPE_CREDIT,
                'monnify_reference' => $eventData->transactionReference
            ];

            $this->transactionRepo->create($data);
        }
    }

    private function computeSHA512TransactionHash($stringifiedData, $clientSecret)
    {
        $computedHash = hash_hmac('sha512', $stringifiedData, $clientSecret);
        return $computedHash;
    }
}

resources/views/wallet/fund.blade.php
@extends('layouts.master')

@section('title')
    Fund Wallet
@endsection

@section('content')

    <section class="wallet">
        <div class="row">
            <div class="columns large-6 small-12 large-offset-3">
                <h2>Fund Wallet</h2>

                <div style=" border-color: black; border-radius: 10px;">
                    <h5> Pay to Virtual Bank Account</h5>
{{--                    <p>Note: 1% service charge is deducted</p>--}}
                    <h6>Bank Name: {{$bank->bank_name}}</h6>
                    <h6>Account Name: {{$bank->account_name}}</h6>
                    <h6>Account Number: {{$bank->account_no}}</h6>

                    <br>
                    <br>
                    <h4>OR</h4>
                </div>


                    <form action="{{ route('fund.wallet.create') }}" method="post" id="fund-wallet">
                    @csrf
                    <p><label><br>
                            <span class="wpcf7-form-control-wrap email">
                                <input name="amount" value="" size="40" id="amount"
                                       class="wpcf7-form-control wpcf7-text wpcf7-email wpcf7-validates-as-required wpcf7-validates-as-email"
                                       placeholder="Amount" type="number">
                            </span>
                        <br>
                        </label>

                        <label><span style="font-weight: bold">Payment Method</span> <br><br>
                            <span class="wpcf7-form-control-wrap email">
                                <input name="payment_method" value="monnify"
                                       class="wpcf7-form-control wpcf7-text wpcf7-email payment_method wpcf7-validates-as-required wpcf7-validates-as-email"
                                       placeholder="Amount" type="radio" checked> Monnify

                                <input name="payment_method" value="paystack"
                                       class="wpcf7-form-control wpcf7-text wpcf7-email payment_method wpcf7-validates-as-required wpcf7-validates-as-email"
                                       placeholder="Amount" type="radio"> Paystack
                            </span>
                        </label>
                    </p>

                    <p><input value="Proceed" class="wpcf7-form-control wpcf7-submit" type="submit"><span class="ajax-loader"></span>
                    </p>
                    <div class="wpcf7-response-output wpcf7-display-none"></div>

                </form>

                <div id="confirmation">
                    <h5>You are about to make payment of ₦<span class="confirmation-amount"></span></h5>
                    <h5>Transaction fee is ₦<span class="transaction-fee">2.00</span></h5>
                    <h4>Total is ₦<span class="total-fee">2.00</span></h4>
                    <div>
                        <button id="pay">Pay</button>
                        <button id="changeAmount">Change Amount</button>
                    </div>
                </div>
            </div>
        </div>
    </section>

@endsection

@section('scripts')
    @include('scripts.wallet.fund')
@endsection

resources/views/wallet/index.blade.php
@extends('layouts.master')

@section('title')
    My Wallet
@endsection

@section('content')

    <section class="wallet">
        <div class="row">
            <div class="columns large-4 small-12">
                <div class="wallet-card">
                    <span class="balance">₦ {{ $wallet->current_balance }}</span>
                    <span>Current Balance</span>
                </div>
            </div>
            <div class="columns large-4 small-12">
                <div class="wallet-card">
                    <span class="balance">₦ {{ $wallet->spent }}</span>
                    <span>Amount Spent</span>
                </div>
            </div>
            <div class="columns large-4 small-12">
                <div class="wallet-card">
                    <span class="balance">₦ {{ $wallet->earned }}</span>
                    <span>Amout Credited</span>
                </div>
            </div>
        </div>

        <div class="row m-t-50">
            <div class="columns large-12">
                <div class="buttons-box">
                    <a href={{ route('fund.wallet') }} class="button">Fund Wallet</a>
{{--                    <a href="#" class="button">Buy Data</a>--}}
{{--                    <a href="#" class="button">Buy VTU</a>--}}
                </div>

            </div>
        </div>

        <div class="row m-t-50">

            <div class="columns large-12">
                <p class="lead">Recent Transactions</p>
                <table class="hover">
                    <thead>
                    <tr>
                        <th>Type</th>
                        <th>Amount</th>
                        <th>Status</th>
                        <th>Date</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($transactions as $transaction)
                        <tr>
                            <td>{{ $transaction->type_readable }}</td>
                            <td>{{ $transaction->amount }}</td>
                            <td>{{ $transaction->status_readable }}</td>
                            <td>{{ $transaction->created_at }}</td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </section>

@endsection